/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/instruments/loans/loan.hpp>
#include <ql/instruments/loans/fixedrateloans.hpp>
#include <ql/instruments/loans/floatingrateloans.hpp>

